'use strict';

angular.module('crm', [
                        // Standart
                        'ngCookies',
                        'ngTouch',
                        'ngSanitize',
                        'ui.router',

                        // Bower
                        'angularjs-dropdown-multiselect',
                        'ui.bootstrap.showErrors',
                        'ui.sortable',
                        'ngStorage',
                        'farbtastic',
                        'angularModalService',
                        'flow',
                        'angular-loading-bar',
                        'ngAnimate',
                        'smart-table',
                        'st-ratio',
                        'toggle-switch',
                        'ngCsv',
                        'oc.lazyLoad',
                        'ui.bootstrap',
                        'pascalprecht.translate',

                        // Mine
                        'GlobalVarsService',
                        'HCCategoriesService',
                        'EventsService',
                        'AuthApiService',
                        'ThemeColorChangerService',
                        'DataStorageService',
                        'SitesSetupService',
                        'ProcessorSetupService',
                        'ClientSetupService',
                        'UserSetupService',
                        'SearchSetupService',
                        'CustomerSetupService',
                        'ChartInitService',
                        'DebounceService',
                        'ChargebackSetupService',
                        'ExportSetupService',
                        'DeclineSetupService',
                        'CampaignSetupService',
                        'ScrollService',
                        'DataProcessingService',
                        'ReportsSetupService',
                        'first-letter-filter',
                        'campaignfield-setup',
                        'email-validation-directive',
                        'double-SiteIDe-select',
                        'textRange-input-directive',
                        'barchart-directive',
                        'dotted-linechart-directive',
                        'piechart-directive',
                        'linechart-directive',
                        'donutchart-directive',
                        'when-scrolled-directive',
                        'combo-directive',
                        'checkbox-directive',
                        'select-directive',
                        'radio-list-directive',
                        'show-error-directive',
                        'text-input-directive',
                        'color-tiles-directive',
                        'portlet-header-directive',
                        'date-picker-directive',
                        'table-directive',
                        'select-clients-dates',
                        'csv-import-directive',
                        'ui-notification',
                        'ui.tinymce',
                        'duScroll',
                        'FileReaderService',
                        'FileDownloaderService',
                        'ngMask',
                        'read-more-directive'
                      ])
